version: '3'

services:
  postgis:
    image: mdillon/postgis:9.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: matrikkelen
      POSTGRES_PASSWORD: matrikkelen
      POSTGRES_DB: matrikkelen
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb.d/restore.sh:/docker-entrypoint-initdb.d/xrestore.sh
      - ./initdb.d/rename.sql:/docker-entrypoint-initdb.d/xschemarename.sql
      - ./matrikkelen.tmp/Basisdata_0000_Norge_25833_MatrikkelenAdresseLeilighetsniva_PostGIS.backup:/tmp/MatrikkelenAdresseLeilighetsniva.backup
    restart: always

volumes:
  db_data:
